### ISSUE TITLE
Z-Fighting

### ISSUE THREAD

**Issue by Resparc** [the-pink-hacker/classic-3d-redux#1]
is there a way to fix the z-fighting that happens when two blocks overlap? I love this pack but the glitchy textures overlapping can be distracting.

**Comment by the-pink-hacker** [comment]
This is an issue I'm very much aware of. Before I exit alpha and go into beta, I do plan on fixing it.

Expect to see a fix for this within the next month-ish.

**Comment by the-pink-hacker** [comment]
A month, a day, basically the same thing. Just added rudimentary z-fighting detection to my build tool (f6407c4f1843fe023cea7ee1f9e7defaa718f839, the-pink-hacker/mcpacker@ce207a9e173f66b3534cec7a912fd49e4289d35d). Currently, Classic 3D is only setup to detect and fix it on block edges. Here is the oak door for instance:

![2024-07-19_21 25 11](https://github.com/user-attachments/assets/ea9af43f-391c-449c-adce-3641da1fbd88)
![2024-07-19_21 25 32](https://github.com/user-attachments/assets/266a83d5-1051-4e04-9392-c26041c8f244)

This doesn't work within blocks just yet so I'm leaving this issue open for now. Like 90% of the z-fighting will be resolved by next alpha.

**Comment by the-pink-hacker** [comment]
At this point it's now possible to add specific z-fighting fixes for blocks. I feel that it would be better to from now on create issue tickets per block that experiences z-fighting.
